<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ronald G. Thomas">
<meta name="dcterms.date" content="2026-08-18">
<meta name="description" content="A review of how peer graduate biostatistics and statistical computing courses handle generative AI, from outright bans to required use, followed by a policy proposal for PHB 228 at UCSD.">

<title>A Review and Proposal for Policy Regarding Generative AI Use in Graduate Biostatistics Courses – focusonr</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-d1f979f567abd94e3c058709025db867.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&amp;family=Open+Sans:ital,wght@0,400;0,600;1,400&amp;family=Fira+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/0fba9333d8.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<!-- Custom meta tags for social sharing -->
<meta property="og:site_name" content="focusonr">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@rgt47">

<!-- Add responsive features -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Add analytics if needed -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-XXXXXXXX');
</script> -->

<!-- Add custom javascript -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Remove code tools button completely
  const codeButton = document.querySelector('.code-tools-button');
  if (codeButton) {
    codeButton.remove();
  }

  // Smooth scrolling for in-page anchor links (skip listing category elements)
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    if (anchor.closest('.quarto-listing-category')) return;
    anchor.addEventListener('click', function (e) {
      const target = document.querySelector(this.getAttribute('href'));
      if (!target) return;
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth' });
    });
  });
});
</script>


<meta property="og:title" content="A Review and Proposal for Policy Regarding Generative AI Use in Graduate Biostatistics Courses – focusonr">
<meta property="og:description" content="A review of how peer graduate biostatistics and statistical computing courses handle generative AI, from outright bans to required use, followed by a policy proposal for PHB 228 at UCSD.">
<meta property="og:image" content="https://focusonr.org/posts/pub-ai-course-policy-survey/analysis/report/media/images/hero.jpg">
<meta property="og:site_name" content="focusonr">
<meta name="twitter:title" content="A Review and Proposal for Policy Regarding Generative AI Use in Graduate Biostatistics Courses – focusonr">
<meta name="twitter:description" content="A review of how peer graduate biostatistics and statistical computing courses handle generative AI, from outright bans to required use, followed by a policy proposal for PHB 228 at UCSD.">
<meta name="twitter:image" content="https://focusonr.org/posts/pub-ai-course-policy-survey/analysis/report/media/images/hero.jpg">
<meta name="twitter:creator" content="@rgt47">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">focusonr</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://rgtlab.org"> 
<span class="menu-text">rgtlab.org</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/rgt47"> <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rgt47"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#motivations" id="toc-motivations" class="nav-link" data-scroll-target="#motivations">Motivations</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">Objectives</a></li>
  </ul></li>
  <li><a href="#course-ai-policies-a-taxonomy-of-institutional-responses" id="toc-course-ai-policies-a-taxonomy-of-institutional-responses" class="nav-link" data-scroll-target="#course-ai-policies-a-taxonomy-of-institutional-responses">Course AI Policies: A Taxonomy of Institutional Responses</a>
  <ul class="collapse">
  <li><a href="#banned-or-heavily-restricted" id="toc-banned-or-heavily-restricted" class="nav-link" data-scroll-target="#banned-or-heavily-restricted">Banned or Heavily Restricted</a></li>
  <li><a href="#permitted-with-citation" id="toc-permitted-with-citation" class="nav-link" data-scroll-target="#permitted-with-citation">Permitted with Citation</a></li>
  <li><a href="#encouraged-or-required" id="toc-encouraged-or-required" class="nav-link" data-scroll-target="#encouraged-or-required">Encouraged or Required</a></li>
  <li><a href="#taught-as-explicit-curricular-content" id="toc-taught-as-explicit-curricular-content" class="nav-link" data-scroll-target="#taught-as-explicit-curricular-content">Taught as Explicit Curricular Content</a></li>
  <li><a href="#summary-table" id="toc-summary-table" class="nav-link" data-scroll-target="#summary-table">Summary Table</a></li>
  <li><a href="#a-broader-sweep-silence-is-the-norm" id="toc-a-broader-sweep-silence-is-the-norm" class="nav-link" data-scroll-target="#a-broader-sweep-silence-is-the-norm">A Broader Sweep: Silence Is the Norm</a></li>
  </ul></li>
  <li><a href="#two-curricular-models" id="toc-two-curricular-models" class="nav-link" data-scroll-target="#two-curricular-models">Two Curricular Models</a>
  <ul class="collapse">
  <li><a href="#the-jhu-model-ai-as-professional-infrastructure" id="toc-the-jhu-model-ai-as-professional-infrastructure" class="nav-link" data-scroll-target="#the-jhu-model-ai-as-professional-infrastructure">The JHU Model: AI as Professional Infrastructure</a></li>
  <li><a href="#the-usc-model-coding-without-learning-to-code" id="toc-the-usc-model-coding-without-learning-to-code" class="nav-link" data-scroll-target="#the-usc-model-coding-without-learning-to-code">The USC Model: Coding Without Learning to Code</a></li>
  </ul></li>
  <li><a href="#why-learn-computing-when-ai-can-code" id="toc-why-learn-computing-when-ai-can-code" class="nav-link" data-scroll-target="#why-learn-computing-when-ai-can-code">‘Why Learn Computing When AI Can Code?’</a></li>
  <li><a href="#pedagogical-framings" id="toc-pedagogical-framings" class="nav-link" data-scroll-target="#pedagogical-framings">Pedagogical Framings</a></li>
  <li><a href="#risks-and-concerns" id="toc-risks-and-concerns" class="nav-link" data-scroll-target="#risks-and-concerns">Risks and Concerns</a></li>
  <li><a href="#recommendations-for-phb-228" id="toc-recommendations-for-phb-228" class="nav-link" data-scroll-target="#recommendations-for-phb-228">Recommendations for PHB 228</a></li>
  <li><a href="#things-to-watch-out-for" id="toc-things-to-watch-out-for" class="nav-link" data-scroll-target="#things-to-watch-out-for">Things to Watch Out For</a></li>
  <li><a href="#lessons-learned" id="toc-lessons-learned" class="nav-link" data-scroll-target="#lessons-learned">Lessons Learned</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#opportunities-for-improvement" id="toc-opportunities-for-improvement" class="nav-link" data-scroll-target="#opportunities-for-improvement">Opportunities for Improvement</a></li>
  <li><a href="#wrapping-up" id="toc-wrapping-up" class="nav-link" data-scroll-target="#wrapping-up">Wrapping Up</a>
  <ul class="collapse">
  <li><a href="#what-did-we-learn" id="toc-what-did-we-learn" class="nav-link" data-scroll-target="#what-did-we-learn">What Did We Learn?</a></li>
  </ul></li>
  <li><a href="#see-also" id="toc-see-also" class="nav-link" data-scroll-target="#see-also">See Also</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#lets-connect" id="toc-lets-connect" class="nav-link" data-scroll-target="#lets-connect">Let’s Connect</a>
  <ul class="collapse">
  <li><a href="#related-posts-in-this-cluster" id="toc-related-posts-in-this-cluster" class="nav-link" data-scroll-target="#related-posts-in-this-cluster">Related posts in this cluster</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Review and Proposal for Policy Regarding Generative AI Use in Graduate Biostatistics Courses</h1>
  <div class="quarto-categories">
    <div class="quarto-category">teaching</div>
    <div class="quarto-category">ai-policy</div>
    <div class="quarto-category">statistical-computing</div>
    <div class="quarto-category">higher-education</div>
    <div class="quarto-category">phb228</div>
  </div>
  </div>

<div>
  <div class="description">
    A review of how peer graduate biostatistics and statistical computing courses handle generative AI, from outright bans to required use, followed by a policy proposal for PHB 228 at UCSD.
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ronald G. Thomas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- ============================================================================
AUTHOR PROVIDES — concrete inputs the blogger must supply

YAML FRONT MATTER
  [x] title, date, categories, description, image filled in
  [ ] draft: false    — flip when ready

IMAGES (4 total: hero + 3 ambiance, all in media/images/)
  [ ] Hero image (80% width)
  [ ] Ambiance image 1 — after Objectives
  [ ] Ambiance image 2 — after the curricular-content models section
  [ ] Ambiance image 3 — before Lessons Learnt
  [ ] media/images/README.md — sources + attribution for every image

SOURCE
  Adapted from
  ~/prj/tch/07-phb228-stat-computing/phb228-2026/lectures/
  report_ai_in_stat_computing_courses.md, a survey report prepared for
  PHB 228 (Statistical Computing, UCSD). This post is a condensed
  translation of that report into blog format. Content has been
  reorganised and shortened for narrative flow; no policy claims have
  been added beyond the source report, and the source report's
  epistemic caveats (which peer-course claims are independently
  verified against a current public syllabus, versus carried forward
  from an early-2025 review) are preserved rather than smoothed over.
============================================================================ -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/images/hero.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
<p><em>A statistician who cannot explain a line of AI-generated code cannot defend it to an FDA reviewer, and the syllabus is where that expectation gets set.</em></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Graduate-level statistical computing courses have adopted strikingly different stances toward generative AI, from outright bans on assignment code to a required subscription to a paid coding assistant. This post surveys that landscape across six peer courses (Carnegie Mellon, Johns Hopkins, UC Berkeley, UNC, Michigan, UIUC), and compares two contrasting curricular models for teaching AI as content rather than merely permitting it. It then works through the recurring arguments for why computing should still be taught when a language model can generate plausible statistical code. It closes with recommendations for PHB 228 (Statistical Computing, UCSD), the course this survey was originally prepared for.</p>
<p>The original report was written in March 2026 against training knowledge current through May 2025. A subsequent verification pass in August 2026 re-checked several claims against currently accessible course syllabi; where a claim could be confirmed, it is marked as such, and where it could not, that is stated plainly rather than presented as settled.</p>
<section id="motivations" class="level2">
<h2 class="anchored" data-anchor-id="motivations">Motivations</h2>
<ul>
<li>Course AI policies written in 2023 or 2024 are already stale. Instructors need a current cross-section of what peer programs are actually doing, not a folk sense of it.</li>
<li>‘Permitted with citation’ is the most common policy, but it hides real variation: some courses pair it with institutional guardrails (AI-detection screening, Honor Court referral), others leave it entirely to student disclosure.</li>
<li>The ‘why learn computing when AI can code’ question is unavoidable in class, and having five distinct, named arguments (validation, accountability, judgment, debugging, amplification) ready is more useful than one vague appeal to rigor.</li>
<li>The tooling itself has moved on since most published course policies were written. Autocomplete-style suggestions and agentic, multi-step coding tools raise different pedagogical questions, and few syllabi currently distinguish between them.</li>
</ul>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<ol type="1">
<li>Classify peer-course AI policies into a small taxonomy (banned, permitted with citation, encouraged or required, taught as curricular content), and note which classifications are currently verified against a public syllabus versus carried forward from an earlier review.</li>
<li>Contrast two curricular models for treating AI as course content: Johns Hopkins’ ‘professional infrastructure’ approach and a newer USC model built around prompting rather than writing code.</li>
<li>Catalog the recurring pedagogical metaphors (pair programmer, Bloom’s taxonomy, driver versus passenger, scaffolded integration) and extend them to the 2026 distinction between autocomplete-style assistance and agentic coding.</li>
<li>Translate the survey into concrete recommendations for PHB 228’s AI policy, curricular content, and framing.</li>
</ol>
<p><img src="media/images/ambiance1.jpg" class="img-fluid"></p>
</section>
</section>
<section id="course-ai-policies-a-taxonomy-of-institutional-responses" class="level1">
<h1>Course AI Policies: A Taxonomy of Institutional Responses</h1>
<p>Peer courses sort into four broad categories: banned or heavily restricted, permitted with citation, encouraged or required, and taught as explicit curricular content. The categories are not mutually exclusive; a course can both study AI’s failure modes and forbid its use on graded assignments.</p>
<section id="banned-or-heavily-restricted" class="level2">
<h2 class="anchored" data-anchor-id="banned-or-heavily-restricted">Banned or Heavily Restricted</h2>
<p><strong>CMU 36-750 (Statistical Computing)</strong>, taught by Christopher Genovese, bans, as of the syllabus version accessed in August 2026, feeding assignment problems to a large language model, confining permitted use to documentation lookup and general conceptual questions. This is a more restrictive stance than ‘taught as content’ alone would suggest, and it coexists with a research orientation elsewhere in the CMU statistics curriculum that studies AI’s strengths and failure modes. A course can prohibit a tool on assignments while still studying it as a subject.</p>
<p><strong>CMU 36-350 (Statistical Computing)</strong>, currently taught by Benjamin LeRoy, has historically prohibited AI-generated code on certain assignments so that students first demonstrate personal mastery of programming concepts. A current syllabus PDF exists but its AI-policy language was not independently re-confirmed in the August 2026 pass; this description should be read as last verified in early 2025.</p>
<p><strong>University of Michigan BIOSTAT 615</strong> (as reported in the original early-2025 review; not re-verified against a current syllabus in the August 2026 pass) has maintained strict academic integrity policies that predate the LLM era. The course has not issued a blanket ban, but its emphasis on implementing algorithms from scratch (an EM algorithm, an MCMC sampler) implicitly constrains AI use, since the pedagogical goal is understanding computational internals rather than producing working code per se.</p>
</section>
<section id="permitted-with-citation" class="level2">
<h2 class="anchored" data-anchor-id="permitted-with-citation">Permitted with Citation</h2>
<p>This remains the most common policy category, though it covers more variation than the label suggests.</p>
<p><strong>UCSD PHB 228</strong>, per its 2026 syllabus, requires that ‘Use of AI tools (such as ChatGPT) is permitted, as long as proper credit is given by citing the explicit prompts that were used,’ positioning AI alongside other cited sources (textbooks, Stack Overflow, peer consultation).</p>
<p><strong>UC Berkeley STAT 243</strong>, taught by Chris Paciorek, permitted AI use as of the 2023-2024 offering (not re-verified against a current syllabus in the August 2026 pass). Students were required to document which tools were used, what prompts were given, and how the output was modified, while remaining fully responsible for the correctness of submitted work regardless of its provenance.</p>
<p><strong>UNC BIOS 735</strong>, taught by Naim Rashid, turns out to require more structure than a simple citation rule. Its syllabus, accessed August 2026, includes a dedicated ‘Use of Generative AI’ section deferring to UNC’s university-wide Generative AI committee policy, prohibiting AI as a substitute for completing readings, computation, or written output, and permitting AI-detection screening with Honor Court referral. This is better described as ‘permitted with institutional guardrails’ than plain permitted-with-citation.</p>
<p><strong>UIUC STAT 428</strong> (as reported in the original early-2025 review; not re-verified against a current syllabus in the August 2026 pass) permits AI tools as part of the broader ecosystem of computational resources available to students. This reflects a pragmatic view that AI is already part of the professional computing environment graduates will enter.</p>
</section>
<section id="encouraged-or-required" class="level2">
<h2 class="anchored" data-anchor-id="encouraged-or-required">Encouraged or Required</h2>
<p><strong>Johns Hopkins Biostatistics 140.776</strong>, in Leonardo Collado Torres’s 2024 offering, required students to obtain and use GitHub Copilot Pro, treating it as professional infrastructure comparable to RStudio or Git rather than a shortcut. The department addressed the resulting equity concern with institutional subscriptions. This description reflects the 2024 offering specifically; later public course materials for 140.776 were not located in the August 2026 pass, so the Copilot Pro requirement should be read as offering-specific rather than a confirmed ongoing commitment.</p>
</section>
<section id="taught-as-explicit-curricular-content" class="level2">
<h2 class="anchored" data-anchor-id="taught-as-explicit-curricular-content">Taught as Explicit Curricular Content</h2>
<p>Several courses treat AI as a topic of study rather than only a policy question. CMU’s Department of Statistics and Data Science has studied LLM capabilities for statistical tasks, an orientation that pairs, as noted above, with 36-750’s current ban on using those same tools for graded work. UC Berkeley STAT 243 discusses how AI-assisted workflows affect reproducibility. PHB 228 uses a ‘bookend’ structure: Lecture 1 frames the course rationale around evaluation capability and regulatory accountability, and Lecture 19 returns with a detailed taxonomy of what AI does well and poorly for statisticians, after students have accumulated a term’s worth of firsthand experience.</p>
</section>
<section id="summary-table" class="level2">
<h2 class="anchored" data-anchor-id="summary-table">Summary Table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Course</th>
<th>Institution</th>
<th>Policy Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>STAT 243</td>
<td>UC Berkeley</td>
<td>Permitted with citation</td>
</tr>
<tr class="even">
<td>140.776</td>
<td>Johns Hopkins</td>
<td>Required (Copilot Pro, 2024 offering)</td>
</tr>
<tr class="odd">
<td>36-750</td>
<td>CMU</td>
<td>Banned on assignments</td>
</tr>
<tr class="even">
<td>36-350</td>
<td>CMU</td>
<td>Restricted on some assignments</td>
</tr>
<tr class="odd">
<td>BIOS 735</td>
<td>UNC</td>
<td>Permitted with institutional guardrails</td>
</tr>
<tr class="even">
<td>BIOSTAT 615</td>
<td>U Michigan</td>
<td>Implicitly restricted</td>
</tr>
<tr class="odd">
<td>STAT 428</td>
<td>UIUC</td>
<td>Permitted with citation</td>
</tr>
<tr class="even">
<td>PHB 228</td>
<td>UCSD</td>
<td>Permitted with citation</td>
</tr>
</tbody>
</table>
<p>Categories for STAT 243, BIOSTAT 615, and STAT 428 reflect the original early-2025 review and were not independently re-verified against a current public syllabus. Categories for 36-750, BIOS 735, and 140.776 were updated in August 2026 against currently accessible course syllabi.</p>
</section>
<section id="a-broader-sweep-silence-is-the-norm" class="level2">
<h2 class="anchored" data-anchor-id="a-broader-sweep-silence-is-the-norm">A Broader Sweep: Silence Is the Norm</h2>
<p>The eight courses above were not chosen because they are the only biostatistics computing courses with a public AI policy; they were chosen because they are the only ones a systematic search turned up with one. A subsequent sweep of roughly twenty additional graduate biostatistics programs, including Harvard, UCLA, the University of Pennsylvania, the University of Washington, Yale, Minnesota, Emory, Vanderbilt, Duke, Boston University, Pittsburgh, Iowa, Rutgers, Wisconsin, Colorado, Ohio State, USC, Brown, UAB, and MUSC, found no additional course-specific policy that could be confirmed against an actual syllabus text.</p>
<p>Two of those checks are worth citing directly because they are verified negatives, not merely absences of evidence:</p>
<ul>
<li><strong>Harvard Biostatistics 776, R. Peng’s syllabus</strong> (accessed August 2026), fetched directly, contains no generative-AI policy language of any kind. <a href="https://rdpeng.github.io/Biostat776/syllabus.html" class="uri">https://rdpeng.github.io/Biostat776/syllabus.html</a></li>
<li><strong>UCLA Biostat 203B, H. Zhou’s syllabus</strong> (posted for the 2023 winter offering; accessed August 2026), fetched directly, likewise contains no generative-AI policy language. <a href="https://ucla-biostat-203b.github.io/2023winter/syllabus/syllabus.html" class="uri">https://ucla-biostat-203b.github.io/2023winter/syllabus/syllabus.html</a></li>
</ul>
<p>Where a program-level statement exists at all, it is typically an institutional policy that defers the actual decision to individual instructors, rather than a course-specific rule. The University of Washington’s center-level guidance page (accessed August 2026) is one example: it states explicitly that the university has no single policy and that each instructor sets their own. <a href="https://teaching.washington.edu/course-design/ai/ai-course-policies/" class="uri">https://teaching.washington.edu/course-design/ai/ai-course-policies/</a></p>
<p>One additional lead, a University of Pennsylvania course (BSTA6700) whose posted syllabus PDF could not be reliably parsed, surfaced a search-engine snippet suggesting the course frames a chatbot as a ‘computational and programming assistant’ via structured prompting. That snippet is not a verified quotation from the syllabus itself and is deliberately not cited as a source here; it is noted only so a future revision knows where to look.</p>
<p>The practical implication is that CMU 36-750’s explicit ban and UNC BIOS 735’s guardrails are not one data point among many similarly documented peer policies; they are two of a very small number of biostatistics computing courses anywhere with a publicly checkable, course-specific generative-AI policy at all. Most programs, so far as this search could determine, have simply not published one.</p>
</section>
</section>
<section id="two-curricular-models" class="level1">
<h1>Two Curricular Models</h1>
<section id="the-jhu-model-ai-as-professional-infrastructure" class="level2">
<h2 class="anchored" data-anchor-id="the-jhu-model-ai-as-professional-infrastructure">The JHU Model: AI as Professional Infrastructure</h2>
<p>Collado Torres’s JHU 140.776 treated GitHub Copilot Pro as essential infrastructure, analogous to RStudio or Git: a professional tool students must learn to operate, not a shortcut. The course covered setup and configuration, critical evaluation of suggestions (with exercises exposing cases where Copilot generates plausible but incorrect statistical code), workflow integration (when to accept, modify, or reject a suggestion), and documentation practices for recording AI contributions in reproducible analyses. The pedagogical emphasis shifted from ‘can you write this code?’ to ‘can you evaluate, debug, and improve AI-generated code?’</p>
</section>
<section id="the-usc-model-coding-without-learning-to-code" class="level2">
<h2 class="anchored" data-anchor-id="the-usc-model-coding-without-learning-to-code">The USC Model: Coding Without Learning to Code</h2>
<p>A contrasting model appears in Bien and Mukherjee’s (2025) account of a required MBA data-science course at USC. Rather than teaching R or Python syntax directly, the course teaches students to prompt GitHub Copilot to generate code, with class time devoted to specifying analytical intent, interpreting output, and catching errors, rather than writing code from scratch. The authors frame this as appropriate for a terminal audience (MBA students who will manage, not personally implement, analyses), and explicitly do not recommend the same approach for students who must become independent, accountable statistical programmers, which describes PHB 228’s audience. The contrast is instructive: the correct AI policy for a statistical computing course depends on whether its graduates are expected to write and defend code themselves, or to direct others (including AI systems) who do.</p>
<p><img src="media/images/ambiance2.jpg" class="img-fluid"></p>
</section>
</section>
<section id="why-learn-computing-when-ai-can-code" class="level1">
<h1>‘Why Learn Computing When AI Can Code?’</h1>
<p>This question has been unavoidable in statistical computing courses since 2023. It is the computational analogue of ‘why learn arithmetic when calculators exist,’ but with greater force, because a language model can generate sophisticated statistical code that appears to work correctly. Five arguments recur across the courses surveyed.</p>
<p><strong>The validation argument.</strong> You cannot evaluate what you do not understand. A bootstrap confidence interval that ignores clustering structure, a simulation study that skips common random numbers, or a mixed-effects model with a misspecified random-effects structure will all run without error. Only a trained statistician can identify these failures. PHB 228’s Lecture 1 states this directly: ‘AI-generated code may be syntactically valid but statistically incorrect.’</p>
<p><strong>The accountability argument.</strong> In regulated settings (FDA submissions, clinical trial analyses), a statistician must be able to explain and defend every analytical decision. ‘The AI suggested it’ is not an acceptable answer to a statistical reviewer, and no regulatory framework currently contemplates AI-generated analyses the submitting statistician cannot fully explain. The ICH E9 guideline and its E9(R1) addendum on estimands presuppose human judgment at every stage.</p>
<p><strong>The judgment argument.</strong> Choice of estimator, handling of missing data, model specification, and sensitivity-analysis design all require understanding of the scientific question and the data-generating process, not just syntactic fluency.</p>
<p><strong>The debugging argument.</strong> When AI-generated code fails, the user needs enough understanding to diagnose and fix the problem. Debugging requires deeper knowledge than generation.</p>
<p><strong>The amplification argument.</strong> AI is most powerful in the hands of a skilled practitioner. Reframed, the question is not ‘AI versus human’ but ‘AI with a skilled human versus AI with an unskilled human.’</p>
<p>The <em>Journal of Statistics and Data Science Education</em> maintains a standing article collection, ‘Generative AI in Statistics and Data Science Education’ (established June 2025, edited by Juana Sanchez), that has published on exactly this shift from code production to code evaluation. Bien and Mukherjee (2025), discussed above, is one entry in that collection.</p>
</section>
<section id="pedagogical-framings" class="level1">
<h1>Pedagogical Framings</h1>
<p>Four metaphors recur in how instructors talk about AI integration, and a fifth has become necessary as the tooling has changed.</p>
<p><strong>AI as pair programmer.</strong> The AI serves as ‘navigator’ (suggesting code, catching syntax errors) while the student remains ‘driver’ (making design decisions, evaluating suggestions). This avoids the false dichotomy of ‘use AI’ versus ‘do not use AI,’ and has been adopted informally at JHU and Berkeley.</p>
<p><strong>Bloom’s taxonomy.</strong> AI excels at the lower cognitive levels (Remember, Understand, Apply): recalling syntax, explaining concepts, applying standard methods. The higher levels (Analyze, Evaluate, Create) remain firmly in the human domain. The tension is that if students never practice the lower-level tasks themselves, they may lack the foundation needed for the higher-level work AI cannot do. This tension is unresolved in the literature.</p>
<p><strong>Driver versus passenger.</strong> A student who prompts an AI and submits the output is a passenger who has abdicated intellectual responsibility. A student who treats AI suggestions as one input among many, while retaining control of analytical direction, is a driver. PHB 228’s Lecture 19 offers a related image: ‘A surgeon uses robotic assistance but understands every cut.’</p>
<p><strong>Scaffolded integration.</strong> Restrict AI early, when foundational skills are still forming, then progressively permit or require it as those skills develop, analogous to introducing calculators only after arithmetic is secure. No major course has fully implemented this model as of the original report; JHU’s ‘require Copilot Pro throughout’ approach is a deep-end alternative that assumes critical-evaluation skills develop through immersion instead.</p>
<p><strong>From autocomplete to agentic coding.</strong> The pair-programming and driver/passenger metaphors were developed when ‘AI assistance’ meant inline autocomplete, most visibly GitHub Copilot’s original line-by-line completions. By 2026 the terminology has shifted: agentic coding tools (Claude Code, Copilot’s agent mode, Cursor’s agent mode) plan multi-step tasks, edit multiple files, run tests, and iterate on failures with limited human intervention per step. The informal term ‘vibe coding’ describes accepting an agent’s output with minimal review, precisely the passenger stance the driver/passenger metaphor warns against. This sharpens rather than resolves the pedagogical questions above: an agent that autonomously modifies a simulation study across several files raises the stakes of the validation, judgment, and debugging arguments, because errors can propagate further before a human reviews them. Few published syllabi currently distinguish autocomplete-style assistance from agentic, multi-step use, even though the appropriate level of human oversight differs between the two.</p>
</section>
<section id="risks-and-concerns" class="level1">
<h1>Risks and Concerns</h1>
<p>Five risks recur across the courses and literature surveyed, plus a sixth specific to agentic tools.</p>
<ul>
<li><strong>Over-reliance and deskilling.</strong> Students who rely heavily on AI may fail to develop ‘computational intuition,’ the ability to anticipate what an algorithm will do, estimate how long it should take, or recognize implausible output. This mirrors documented risks of premature calculator reliance in mathematics education.</li>
<li><strong>Inability to debug AI-generated code.</strong> Such code often works in the common case but fails at small samples, near-collinearity, non-convergence, or boundary parameter values, precisely where statistical judgment matters most. PHB 228’s Lecture 19 gives a concrete example: an AI asked for a low-rank matrix approximation used the wrong singular value decomposition convention, producing results ‘subtly wrong in ways that would corrupt downstream inference.’</li>
<li><strong>Academic integrity.</strong> Traditional plagiarism detection cannot identify AI-generated code, and the ‘permitted with citation’ model shifts the integrity question from ‘did you use AI?’ to ‘did you disclose your AI use honestly?’</li>
<li><strong>Equity.</strong> GitHub Copilot Pro and ChatGPT Plus are paid tools; students with fewer resources may be limited to weaker free tiers, compounding an existing ‘rich get richer’ dynamic in which stronger programmers get more out of AI assistance in the first place.</li>
<li><strong>Hallucinated statistical methods.</strong> AI tools can generate code for methods that do not exist, or that combine real methods incorrectly: confidence intervals that mix parametric and nonparametric logic invalidly, optimization routines with fabricated convergence criteria, test statistics with the wrong reference distribution, simulation designs with silently broken variance reduction. These look reasonable and can pass superficial review; only deep methodological knowledge catches them.</li>
<li><strong>Reduced review points under agentic coding.</strong> Agentic tools compress what used to be several discrete human review points (accept one suggested line, run it, inspect the output) into a single review of a larger, multi-file change. A student who reviews a full simulation-study implementation only after it runs successfully may never see the intermediate step where a statistical assumption was built in incorrectly. ‘Vibe coding’ is an acute version of the deskilling and debugging risks above, worth naming explicitly rather than treating as a faster version of ordinary AI-assisted coding.</li>
</ul>
</section>
<section id="recommendations-for-phb-228" class="level1">
<h1>Recommendations for PHB 228</h1>
<p>These recommendations account for PHB 228’s identity as a biostatistics graduate course, its current ‘permitted with citation’ policy, its existing AI content in Lectures 1, 2, and 19, and the professional context its graduates will enter (clinical trials, FDA submissions, epidemiology).</p>
<p><strong>Maintain ‘permitted with citation,’ with refinement.</strong> The policy avoids the impracticality of a ban, the equity cost of requiring a paid tool, and the pedagogical risk of unrestricted use. Two refinements would strengthen it: specify what adequate citation looks like (tool, prompt, how output was modified, the student’s own assessment of correctness), and differentiate by assessment type, restricting AI on early foundational assignments while permitting it fully later, with in-class midterms and finals serving as natural AI-free checkpoints.</p>
<p><strong>Strengthen the curricular content.</strong> The existing bookend structure (Lecture 1, Lecture 19) is well designed. A middle touchpoint during simulation-study design (Weeks 4-5) would reinforce it: have students prompt an AI to design a simulation comparing two estimators, then critically evaluate the generated code for missing common random numbers, missing Monte Carlo standard errors, or inappropriate sample sizes, and correct it.</p>
<p><strong>Emphasize regulatory accountability as a central theme, not one argument among several.</strong> Invoke the FDA explicitly: a reviewer may ask a graduate to justify any analytical decision, and ‘the AI suggested it’ is not an acceptable answer. Connect explicitly to ICH E9 and the estimand framework, and draw examples from the clinical trial context: interim analysis boundaries, missing-data handling in randomized trials, and survival-analysis assumptions.</p>
<p><strong>Prepare students to be AI-skilled professionals.</strong> JHU’s mandatory Copilot Pro is too aggressive for PHB 228’s current context, but the underlying insight, that graduates without AI-assisted coding skills will be at a professional disadvantage, is correct. Normalize AI use in live-coding demonstrations, narrating the evaluation process explicitly, and frame AI proficiency as a career asset alongside R programming and reproducible workflows.</p>
<p><strong>Monitor peer institutions and professional guidance.</strong> CMU 36-750 and UNC BIOS 735 now publish specific, restrictive AI-policy language directly in their syllabi and are worth watching as models. JHU 140.776 and Berkeley STAT 243 are also likely to keep evolving, though their most recent public policy language could not be confirmed in this pass. The <em>JSDSE</em> article collection on generative AI in statistics education is a useful ongoing source. Whether peer policies begin distinguishing autocomplete-style assistance from agentic coding tools is worth tracking as its own question, since almost none do so explicitly yet.</p>
<p><strong>Adopt the ‘trained hands’ framing as a course-level theme.</strong> PHB 228’s Lecture 19 already introduces AI as ‘a power tool that requires trained hands,’ superior to both the defensive (‘AI is a threat to learning’) and promotional (‘AI will transform everything’) alternatives. Elevating it to a syllabus-level statement, reinforced throughout the quarter, states the course’s position plainly: this course trains your hands, AI tools are the power equipment used with them, and without the training the equipment is dangerous rather than transformative.</p>
<p><img src="media/images/ambiance3.jpg" class="img-fluid"></p>
</section>
<section id="things-to-watch-out-for" class="level1">
<h1>Things to Watch Out For</h1>
<ol type="1">
<li><strong>Not every claim below carries the same evidentiary weight.</strong> CMU 36-750’s ban and UNC BIOS 735’s guardrails were confirmed against currently accessible syllabi in August 2026; Berkeley STAT 243, Michigan BIOSTAT 615, and UIUC STAT 428’s policies were not re-verified and should be read as ‘as reported in early 2025.’</li>
<li><strong>The JHU Copilot Pro requirement is offering-specific.</strong> It is documented for the 2024 iteration under Collado Torres; whether it persisted into later years was not confirmed from public materials.</li>
<li><strong>A course studying AI is not the same as a course permitting it.</strong> CMU’s research engagement with LLM capabilities coexists with 36-750’s ban on using those tools for graded work; do not conflate ‘taught as content’ with ‘permitted for assignments.’</li>
<li><strong>‘Permitted with citation’ is not one policy.</strong> UNC’s version comes with AI-detection screening and Honor Court referral; PHB 228’s version rests on student disclosure alone. Comparing courses by category label alone hides this difference.</li>
<li><strong>Autocomplete-era metaphors do not automatically extend to agentic tools.</strong> A policy written with GitHub Copilot’s original inline suggestions in mind may not anticipate a coding agent that edits several files and runs tests unattended.</li>
<li><strong>Course-specific policy text is often LMS-gated.</strong> Several of the ‘unverified’ entries above are for courses that are demonstrably active but whose current syllabus text sits behind a login, consistent with a real policy that simply is not publicly checkable from outside the institution.</li>
<li><strong>Absence of a published policy is not evidence the course ignores AI.</strong> Harvard’s Biostatistics 776 and UCLA’s Biostat 203B were directly fetched and confirmed to contain no AI-policy language, which is itself informative. That does not mean either instructor has no informal practice. It means whatever practice exists is not published.</li>
</ol>
</section>
<section id="lessons-learned" class="level1">
<h1>Lessons Learned</h1>
<p><strong>Conceptual understanding:</strong></p>
<ul>
<li>The policy taxonomy (banned, permitted with citation, encouraged or required, taught as content) is useful but coarser than the reality; the same label can hide very different levels of institutional guardrail.</li>
<li>Five named arguments (validation, accountability, judgment, debugging, amplification) are more durable in classroom discussion than one generic appeal to academic rigor.</li>
<li>The JHU and USC models are not competing answers to the same question; they answer different questions, depending on whether a program’s graduates will write code themselves or direct others who do.</li>
</ul>
<p><strong>Technical and process skills:</strong></p>
<ul>
<li>Verifying a peer-course policy against training knowledge alone is not the same as verifying it against a current syllabus; the two produced materially different answers for three of the six peer courses checked.</li>
<li>A specific, dated URL beats a general institutional claim. The CMU 36-750 and UNC BIOS 735 entries are stronger precisely because they point at a live, checkable document.</li>
</ul>
<p><strong>Gotchas and pitfalls:</strong></p>
<ul>
<li>It is tempting to smooth an ‘unverified’ claim into a confident one once it has been repeated a few times in a document’s own history; resist that, and keep restating the verification status explicitly.</li>
<li>A course’s absence from search results is evidence of an LMS-gated policy, not evidence that no policy exists.</li>
</ul>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<ul>
<li>This is a survey of publicly available course materials, not an exhaustive or systematically sampled review of graduate statistical computing courses nationally.</li>
<li>Three of the eight peer-course entries (Berkeley STAT 243, Michigan BIOSTAT 615, UIUC STAT 428) reflect the original early-2025 review and were not independently re-verified against a current public syllabus in the August 2026 pass.</li>
<li>The JHU 140.776 Copilot Pro requirement is confirmed only for the 2024 offering; continuation into later years is unconfirmed.</li>
<li>Duke STA 663, Harvard BST 260/262, University of Washington BIOST 534/561, and Vanderbilt’s biostatistics computing courses were checked as candidate additions and confirmed active, but no course-specific, publicly accessible AI-policy statement could be located for any of them, so they are not included as verified sources.</li>
<li>A subsequent, broader sweep of roughly twenty additional graduate biostatistics programs (Harvard, UCLA, University of Pennsylvania, University of Washington, Yale, Minnesota, Emory, Vanderbilt, Duke, Boston University, Pittsburgh, Iowa, Rutgers, Wisconsin, Colorado, Ohio State, USC, Brown, UAB, MUSC) found no additional course-specific policy that could be confirmed against an actual syllabus. Two courses, Harvard Biostatistics 776 and UCLA Biostat 203B, were directly fetched and confirmed to contain none. This does not establish that no other program has a policy, only that none was found publicly.</li>
<li>One lead, a University of Pennsylvania course (BSTA6700) whose syllabus PDF resisted text extraction, is deliberately not cited: a search snippet suggested AI-friendly framing, but without a verified quotation from the document itself it does not meet this post’s citation bar.</li>
<li>The ‘agentic coding’ discussion reflects the state of the tooling as of 2026 and the terminology in current general use; it does not reflect any peer course’s published policy language, since few syllabi currently address the distinction explicitly.</li>
</ul>
</section>
<section id="opportunities-for-improvement" class="level1">
<h1>Opportunities for Improvement</h1>
<ol type="1">
<li>Confirm the CMU 36-350, Berkeley STAT 243, Michigan BIOSTAT 615, and UIUC STAT 428 policy descriptions against a current public syllabus, rather than carrying forward the early-2025 characterization.</li>
<li>Check whether JHU 140.776’s Copilot Pro requirement persisted past the 2024 offering, ideally by contacting the department directly rather than relying on search results alone.</li>
<li>Track whether any peer course publishes a policy that explicitly distinguishes autocomplete-style assistance from agentic, multi-step coding tools, since this survey found none that currently do.</li>
<li>Revisit the <em>JSDSE</em> ‘Generative AI in Statistics and Data Science Education’ collection periodically; it is a standing collection, not a one-time publication, and will likely accumulate more course-level case studies like Bien and Mukherjee (2025).</li>
<li>Pilot the Weeks 4-5 simulation-study exercise proposed above in a PHB 228 offering and report back on what it actually surfaces in student work, rather than leaving the proposal untested.</li>
</ol>
</section>
<section id="wrapping-up" class="level1">
<h1>Wrapping Up</h1>
<section id="what-did-we-learn" class="level2">
<h2 class="anchored" data-anchor-id="what-did-we-learn">What Did We Learn?</h2>
<p>The peer-course landscape resists a single clean summary. ‘Permitted with citation’ is the modal policy, but it ranges from pure self-disclosure to institutional AI-detection screening with Honor Court referral behind the identical label. A course can simultaneously study AI as a research subject and ban its use on graded assignments, as CMU 36-750 currently does. And the tooling itself has moved fast enough that the metaphors written for autocomplete-era assistants (pair programmer, driver versus passenger) now need an explicit extension to agentic, multi-step coding tools that few published policies have caught up to yet.</p>
<p>For PHB 228 specifically, the survey does not argue for changing course. The current ‘permitted with citation’ policy, paired with the existing Lecture 1 and Lecture 19 bookend, is well positioned relative to peers. What it argues for is sharpening: naming the five arguments explicitly, treating regulatory accountability as a central theme rather than one argument among several, and elevating ‘a power tool that requires trained hands’ from a single lecture slide to a syllabus-level statement of the course’s position.</p>
</section>
</section>
<section id="see-also" class="level1">
<h1>See Also</h1>
<p><strong>Related posts:</strong></p>
<ul>
<li><a href="../pub-statistical-computing-textbook/">Building a Statistical Computing Textbook in the Age of AI</a>: the companion post on structuring a methods textbook around the same ‘in the Age of AI’ framing.</li>
<li><a href="../rp-code-review-methodology/">Code Review for AI-Assisted R Package Development</a>: a parallel framework for establishing ownership of AI-assisted code after it is written, complementing this post’s classroom-policy focus on AI use while code is being written.</li>
</ul>
<p><strong>Key resources:</strong></p>
<ul>
<li><a href="https://36-750.github.io/course-info/syllabus/">CMU 36-750 syllabus</a> (C. Genovese; accessed August 2026).</li>
<li><a href="https://biodatascience.github.io/statcomp/syllabus.html">UNC BIOS 735 syllabus</a> (N. Rashid; accessed August 2026).</li>
<li><a href="https://rdpeng.github.io/Biostat776/syllabus.html">Harvard Biostatistics 776 syllabus (R. Peng)</a> (accessed August 2026): cited here as a verified negative, containing no AI-policy language.</li>
<li><a href="https://ucla-biostat-203b.github.io/2023winter/syllabus/syllabus.html">UCLA Biostat 203B syllabus (H. Zhou)</a> (2023 winter offering; accessed August 2026): likewise a verified negative.</li>
<li><a href="https://teaching.washington.edu/course-design/ai/ai-course-policies/">University of Washington Center for Teaching and Learning: AI course policies</a> (accessed August 2026): an example of an institution-level statement deferring the actual policy decision to individual instructors.</li>
<li>Bien, J., and Mukherjee, G. (2025). Generative AI for Data Science 101: Coding Without Learning to Code. <em>Journal of Statistics and Data Science Education</em>, 33(2).</li>
<li><em>JSDSE</em> article collection: <a href="https://www.tandfonline.com/journals/ujse21/collections/generative-ai">Generative AI in Statistics and Data Science Education</a> (ed.&nbsp;J. Sanchez, established June 2025; accessed August 2026).</li>
</ul>
<hr>
</section>
<section id="reproducibility" class="level1">
<h1>Reproducibility</h1>
<p>This post carries no executable analysis; it is a narrative translation of a source report. The source document and its full reference list live at <code>~/prj/tch/07-phb228-stat-computing/phb228-2026/lectures/report_ai_in_stat_computing_courses.md</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Item</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Source report</td>
<td><code>report_ai_in_stat_computing_courses.md</code></td>
</tr>
<tr class="even">
<td>Report prepared</td>
<td>March 2026</td>
</tr>
<tr class="odd">
<td>References updated</td>
<td>August 2026</td>
</tr>
<tr class="even">
<td>Blog conversion date</td>
<td>2026-08-18</td>
</tr>
</tbody>
</table>
<hr>
<p><em>Rendered on 2026-08-18 at 11:51 PDT.</em><br> <em>Source: ~/prj/rgtlab/posts/pub-ai-course-policy-survey/index.qmd</em></p>
<hr>
</section>
<section id="lets-connect" class="level1">
<h1>Let’s Connect</h1>
<p>Questions, corrections, or evidence on any of the ‘unverified’ entries above (particularly a current, public syllabus for STAT 243, BIOSTAT 615, or STAT 428, or confirmation of JHU 140.776’s Copilot Pro policy past 2024) are welcome.</p>
<ul>
<li><strong>GitHub</strong>: <a href="https://github.com/rgt47">rgt47</a></li>
<li><strong>Email</strong>: <a href="https://rgtlab.org/contact">Contact form</a></li>
</ul>
<!-- ============================================================================
PRE-PUBLISH QA CHECKLIST — verify each item BEFORE setting draft: false

[ ] YAML
    [x] title, date, categories, description, image filled in
    [x] document-type: "blog"
    [ ] draft: false

[ ] Visual design
    [x] 1 hero image (width=80%) present
    [x] Exactly 3 ambiance images ({.img-fluid} only) after Objectives,
        after the curricular-content models section, and before
        Lessons Learnt
    [x] media/images/README.md attributes every image

[ ] Content quality
    [x] Zero emoji anywhere
    [x] Zero em dashes
    [x] Single quotes preferred over double quotes in prose
    [x] Direct-abstract opening (reference style, no fabricated personal
        narrative not grounded in the source document)
    [x] Epistemic caveats preserved (verified vs. unverified peer-course
        claims), not smoothed into uniform confidence

[ ] Cross-references
    [x] See Also links to the companion textbook post and the code
        review post
    [x] Companion posts' See Also/cluster blocks updated to link back
        here (also fixed stale numbered-post links in the process)

[ ] Render verification
    [x] quarto render index.qmd produces clean HTML with no warnings
    [ ] Hero image displays in /blog/ listing card (not checked in the
        live site build, only in the standalone render)
    [ ] Internal links resolve (site-wide `quarto render` not run to
        confirm cross-post links; visually spot-checked only)

============================================================================ -->
<section id="related-posts-in-this-cluster" class="level2">
<h2 class="anchored" data-anchor-id="related-posts-in-this-cluster">Related posts in this cluster</h2>
<p>This post is part of the <em>Quarto, R Markdown, and Publishing</em> series. Recommended reading order:</p>
<ol type="1">
<li><a href="../pub-multi-language-quarto/">Multi-Language Quarto Documents on macOS</a></li>
<li><a href="../pub-r-script-to-rmd/">Rapid Conversion of Draft R Scripts to Formal Rmd</a></li>
<li><a href="../pub-statistical-computing-textbook/">Building a Statistical Computing Textbook</a></li>
<li><a href="../pub-obs-r-screencasts/">Producing R Coding Videos: OBS Screencasts and Narrated Slide Decks</a></li>
<li><a href="../pub-hosting-quarto-books-netlify/">Hosting a Quarto Book Series on Netlify</a></li>
<li><strong>Generative AI Policies in Graduate Statistical Computing Courses</strong> (this post)</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/focusonr\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Ronald G. Thomas.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rgt47/ryyblog">
      <i class="bi bi-github" role="img" aria-label="Source on GitHub">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<!-- Fix category filtering. itemValues.categories is always a base64+URI-
     encoded comma-joined blob and must be decoded before comparing. The
     incoming `category` argument's encoding is NOT reliable: Quarto's own
     native click path decodes it to plain text before calling
     filterListingCategory, but other call sites (older cached scripts,
     manual calls, other Quarto builds) pass the raw base64 data-category
     value instead. A word like "docker" also happens to be valid-shaped
     base64, so blindly re-decoding an already-plain-text argument silently
     corrupts it rather than failing loudly. Match against both
     interpretations instead of guessing which one applies. -->
<script>
window.addEventListener('DOMContentLoaded', function() {
  setTimeout(function() {
    function decodeCategory(value) {
      try {
        return decodeURIComponent(atob(value));
      } catch (e) {
        return value;
      }
    }

    window.filterListingCategory = function(category) {
      const listingIds = Object.keys(window['quarto-listings']);
      for (const listingId of listingIds) {
        const list = window['quarto-listings'][listingId];
        if (list) {
          if (category === '') {
            list.filter();
          } else {
            const decodedTarget = decodeCategory(category);
            list.filter(function (item) {
              const itemValues = item.values();
              if (itemValues.categories !== null && itemValues.categories !== undefined) {
                const categories = decodeCategory(itemValues.categories)
                  .split(",")
                  .map(c => c.trim());
                return categories.includes(category) || categories.includes(decodedTarget);
              } else {
                return false;
              }
            });
          }
        }
      }
    };
  }, 500);
});
</script>

<!-- PDF view/download button for blog posts -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Only add the button on post pages
  if (window.location.pathname.includes('/posts/') && !window.location.pathname.endsWith('/posts/') && !window.location.pathname.endsWith('/posts/index.html')) {
    var currentPath = window.location.pathname;
    // Handle both /posts/name/ and /posts/name/index.html formats
    var pdfPath;
    if (currentPath.endsWith('/')) {
      pdfPath = currentPath + 'index.pdf';
    } else {
      pdfPath = currentPath.replace('.html', '.pdf');
    }

    // Check if PDF exists first
    fetch(pdfPath, { method: 'HEAD' })
      .then(function(response) {
        if (response.ok) {
          // PDF exists, show download button
          showDownloadButton(pdfPath);
        }
        // If PDF doesn't exist, don't show any button
      })
      .catch(function(error) {
        // Error checking PDF, don't show any button
      });
  }
});

function showDownloadButton(pdfPath) {
  var downloadBtn = document.createElement('div');
  downloadBtn.className = 'pdf-download-button';

  // Get file size if possible
  fetch(pdfPath, { method: 'HEAD' })
    .then(function(response) {
      var size = response.headers.get('Content-Length');
      var sizeText = '';

      if (size) {
        // Convert to MB or KB
        var sizeInMB = size / (1024 * 1024);
        if (sizeInMB >= 1) {
          sizeText = ' (' + sizeInMB.toFixed(1) + ' MB)';
        } else {
          sizeText = ' (' + (size / 1024).toFixed(0) + ' KB)';
        }
      }

      downloadBtn.innerHTML =
        '<div class="alert alert-secondary d-flex align-items-center p-3" role="alert">' +
        '  <a href="' + pdfPath + '" class="btn btn-primary btn-sm me-3" target="_blank">' +
        '    <i class="bi bi-file-pdf me-1"></i> Download PDF' + sizeText +
        '  </a>' +
        '  <span class="small text-muted">View or save a printer-friendly version of this article</span>' +
        '</div>';
    })
    .catch(function() {
      // Basic fallback if we can't get file size
      downloadBtn.innerHTML =
        '<div class="alert alert-secondary d-flex align-items-center p-3" role="alert">' +
        '  <a href="' + pdfPath + '" class="btn btn-primary btn-sm me-3" target="_blank">' +
        '    <i class="bi bi-file-pdf me-1"></i> Download PDF' +
        '  </a>' +
        '  <span class="small text-muted">View or save a printer-friendly version of this article</span>' +
        '</div>';
    });

  // Find where to insert the button (right after the title block)
  var titleBlock = document.querySelector('.quarto-title-meta');
  if (titleBlock) {
    titleBlock.after(downloadBtn);
  }
}


</script>

<style>
.pdf-download-button {
  margin-top: 1rem;
  margin-bottom: 1rem;
}
</style>




</body></html>